#!/bin/bash
#SBATCH --constraint=gpu
#SBATCH --job-name=phy_validation
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=<CPUSPERTASK>
#SBATCH --hint=nomultithread
#SBATCH --output=<OUTPUT>
#SBATCH --time=00:30:00
#SBATCH --gres=gpu:1
#SBATCH --account=s1053
#SBATCH --partition=cscsci

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

which python
python --version
pip list

python physics.py --verbose <PARAMETERIZATION> <BACKEND> <OPTIONS>

exit 0