#!/bin/bash
#SBATCH --constraint=gpu
#SBATCH --job-name=phy_validation
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --hint=nomultithread
#SBATCH --output=out.log
#SBATCH --time=00:30:00
#SBATCH --gres=gpu:1
#SBATCH --account=s1053
#SBATCH --partition=cscsci

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export BACKEND="gtx86"
python physics.py seaice ../seaice/data gtx86 None None